
const LOGIN_USER = 'LOGIN_USER';
const LOGOUT_USER = 'LOGOUT_USER';
const LOADING_START = 'LOADING_START';
const LOADING_STOP = 'LOADING_STOP';

export {
    LOGIN_USER,
    LOGOUT_USER,
    LOADING_START,
    LOADING_STOP,
}